# Usa una imagen base de MySQL
FROM mysql:5.7

# Establece las variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=mi_base_de_datos
ENV MYSQL_USER=usuario
ENV MYSQL_PASSWORD=contraseña

# Expone el puerto 3306
EXPOSE 3306
